from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    OK = "OK"
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_TRANSFORM = "INVALID_TRANSFORM"
    FRAME_NOT_FOUND = "FRAME_NOT_FOUND"
    INVALID_FRAME_CHAIN = "INVALID_FRAME_CHAIN"
    INVALID_QUATERNION = "INVALID_QUATERNION"
    INVALID_ROTATION_MATRIX = "INVALID_ROTATION_MATRIX"
    UNSUPPORTED_ASSET_FORMAT = "UNSUPPORTED_ASSET_FORMAT"
    EMPTY_MESH = "EMPTY_MESH"
    COLLISION_BACKEND_UNAVAILABLE = "COLLISION_BACKEND_UNAVAILABLE"
    IK_FAILED = "IK_FAILED"
    IK_BACKEND_UNAVAILABLE = "IK_BACKEND_UNAVAILABLE"
    IK_DISCONTINUITY = "IK_DISCONTINUITY"
    JOINT_LIMIT_VIOLATION = "JOINT_LIMIT_VIOLATION"
    VELOCITY_LIMIT_VIOLATION = "VELOCITY_LIMIT_VIOLATION"
    ACCELERATION_LIMIT_VIOLATION = "ACCELERATION_LIMIT_VIOLATION"
    JERK_LIMIT_VIOLATION = "JERK_LIMIT_VIOLATION"
    SINGULARITY_RISK = "SINGULARITY_RISK"
    COLLISION_DETECTED = "COLLISION_DETECTED"
    CLEARANCE_TOO_LOW = "CLEARANCE_TOO_LOW"
    PATH_PLANNING_FAILED = "PATH_PLANNING_FAILED"
    RRT_FAILED = "RRT_FAILED"
    PRM_FAILED = "PRM_FAILED"
    PATH_REPAIR_FAILED = "PATH_REPAIR_FAILED"
    TRAJECTORY_GENERATION_FAILED = "TRAJECTORY_GENERATION_FAILED"
    TRAJECTORY_VALIDATION_FAILED = "TRAJECTORY_VALIDATION_FAILED"
    UNSUPPORTED_ROBOT_MODEL = "UNSUPPORTED_ROBOT_MODEL"
    UNSUPPORTED_IK_BACKEND = "UNSUPPORTED_IK_BACKEND"
    BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
    INVALID_AXIS = "INVALID_AXIS"
    INVALID_DISTANCE = "INVALID_DISTANCE"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    TOLERANCE_NOT_MET = "TOLERANCE_NOT_MET"


def not_implemented(message: str):
    from robot_engine.interfaces.result_types import ErrorInfo

    return ErrorInfo(error_code=ErrorCode.NOT_IMPLEMENTED, error_message=message)
