name: robot-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pydantic
  - pyyaml
  - scipy
  - trimesh
  - pinocchio
  - coal
  - ompl
  - open3d
  - meshcat-python
  - pytest
  - pip:
      - -e .[test]
